# Generated by Django 4.1.3 on 2024-10-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성날짜')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드날짜')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='notice.notice')),
            ],
            options={
                'verbose_name': '삽입이미지',
                'verbose_name_plural': '삽입이미지',
            },
        ),
    ]
